apiVersion: v1
kind: PersistentVolume
metadata:
  name: kyc-log
  namespace: ers
  labels:
    type: local
    name: kyc-log
spec:
  storageClassName: manual
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/seamless/log/kyc"
